# Generated by Django 5.1.2 on 2024-11-12 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_usuario_tipo_usuario_usuario_is_aluno_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'ordering': ['nome'], 'verbose_name': 'Aluno', 'verbose_name_plural': 'Alunos'},
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='responsavel',
        ),
        migrations.RemoveField(
            model_name='paimae',
            name='aluno',
        ),
    ]
